namespace :content do
  namespace :topics do 
    task :status => :environment do
      true_topics = [
        "Accountants",
        "Accounting",
        "Acid rain",
        "Acreage allotments",
        "Adhesives",
        "Administrative practice and procedure",
        "Adoption and foster care",
        "Adult education",
        "Advertising",
        "Advisory committees",
        "Aged",
        "Agricultural commodities",
        "Agricultural research",
        "Agriculture",
        "Aid to Families with Dependent Children",
        "Air carriers",
        "Air pollution control",
        "Air rates and fares",
        "Air taxis",
        "Air traffic control",
        "Air traffic controllers",
        "Air transportation",
        "Aircraft",
        "Airmen",
        "Airports",
        "Airspace",
        "Alcohol abuse",
        "Alcohol and alcoholic beverages",
        "Alcoholism",
        "Alien property",
        "Aliens",
        "Alimony",
        "Anchorage grounds",
        "Animal biologics",
        "Animal diseases",
        "Animal drugs",
        "Animal feeds",
        "Animal foods",
        "Animal welfare",
        "Animals",
        "Antibiotics",
        "Antidumping",
        "Antitrust",
        "Armed forces",
        "Armed forces reserves",
        "Arms and munitions",
        "Art",
        "Arts and crafts",
        "Asbestos",
        "Authority delegations (Government agencies)",
        "Aviation safety",
        "Bakery products",
        "Bank deposit insurance",
        "Bankruptcy",
        "Banks, banking",
        "Beer",
        "Bees",
        "Beverages",
        "Bicycles",
        "Bilingual education",
        "Biologics",
        "Black lung benefits",
        "Blind",
        "Blood",
        "Blood diseases",
        "Bonds",
        "Boycotts",
        "Bridges",
        "Brokers",
        "Buildings and facilities",
        "Buses",
        "Business and industry",
        "Cable television",
        "Cacao products",
        "Campaign funds",
        "Cancer",
        "Cargo vessels",
        "Carpets and rugs",
        "Carpools",
        "Cemeteries",
        "Census data",
        "Cereals (food)",
        "Chaplains",
        "Charter flights",
        "Chemicals",
        "Child labor",
        "Child support",
        "Child welfare",
        "Cigars and cigarettes",
        "Citizenship and naturalization",
        "Citrus fruits",
        "Civil defense",
        "Civil disorders",
        "Civil rights",
        "Civil service system",
        "Claims",
        "Classified information",
        "Clemency",
        "Clothing",
        "Coal",
        "Coal conversion program",
        "Coastal zone",
        "Coastal zones",
        "Coffee",
        "Colleges and universities",
        "Color additives",
        "Commodity futures",
        "Common carriers",
        "Communicable diseases",
        "Communications",
        "Communications common carriers",
        "Communications equipment",
        "Community action programs",
        "Community development",
        "Community development block grants",
        "Community facilities",
        "Computer technology",
        "Concessions",
        "Condominiums",
        "Confidential business information",
        "Conflict of interests",
        "Conscientious objectors",
        "Consumer protection",
        "Continental shelf",
        "Cooperatives",
        "Copyright",
        "Cosmetics",
        "CottonSeeds",
        "Counterfeiting",
        "Countervailing duties",
        "Courts",
        "Credit",
        "Credit unions",
        "Crime",
        "Crime insurance",
        "Crop insurance",
        "Cultural exchange programs",
        "Currency",
        "Customs duties and inspection",
        "Dairy products",
        "Dams",
        "Day care",
        "Decorations, medals, awards",
        "Defense communications",
        "Dental health",
        "Dietary foods",
        "Disability benefits",
        "Disaster assistance",
        "Diving",
        "Drug abuse",
        "Drug testing",
        "Drug traffic control",
        "Drugs",
        "Economic statistics",
        "Education",
        "Education of disadvantaged",
        "Education of individuals with disabilities",
        "Educational facilities",
        "Educational research",
        "Educational study programs",
        "Elections",
        "Electric power",
        "Electric power plants",
        "Electric power rates",
        "Electric utilities",
        "Electronic funds transfers",
        "Electronic products",
        "Elementary and secondary education",
        "Emergency medical services",
        "Emergency powers",
        "Employee benefit plans",
        "Employment",
        "Employment taxes",
        "Endangered and threatened species",
        "Energy",
        "Energy conservation",
        "Engineers",
        "Environmental impact statements",
        "Environmental protection",
        "Equal access to justice",
        "Equal educational opportunity",
        "Equal employment opportunity",
        "Estate taxes",
        "Estates",
        "Excise taxes",
        "Executive orders",
        "Explosives",
        "Exports",
        "Fair housing",
        "Fairs and expositions",
        "Family planning",
        "Federal Prison Industries",
        "Federal Reserve System",
        "Federal buildings and facilities",
        "Federal home loan banks",
        "Federally affected areas",
        "Feed grains",
        "Fertilizers",
        "Fire prevention",
        "Firefighters",
        "Fish",
        "Fish (",
        "Fisheries",
        "Fishing",
        "Fishing vessels",
        "Flags",
        "Flammable materials",
        "Flood control",
        "Flood insurance",
        "Flood plains",
        "Food additives",
        "Food assistance programs",
        "Food grades and standards",
        "Food labeling",
        "Food packaging",
        "Food stamps",
        "Foods",
        "Footwear",
        "Foreign Service",
        "Foreign aid",
        "Foreign banking",
        "Foreign claims",
        "Foreign currencies",
        "Foreign investments in U. S.",
        "Foreign officials",
        "Foreign relations",
        "Foreign trade",
        "Foreign trade zones",
        "Forests and forest products",
        "Forgery",
        "Foundations",
        "Fraud",
        "Freedom of information",
        "Freight",
        "Freight forwarders",
        "Frozen foods",
        "Fruit juices",
        "Fruits",
        "Fuel additives",
        "Fuel economy",
        "Gambling",
        "Gas reserves",
        "Gases",
        "Gasohol",
        "Gasoline",
        "General Categories",
        "Genetic diseases",
        "Geothermal energy",
        "Gift taxes",
        "Gifts to Government",
        "Glass and glass products",
        "Gold",
        "Government contracts",
        "Government employees",
        "Government procurement",
        "Government property",
        "Government property management",
        "Government publications",
        "Government securities",
        "Grain sorghum",
        "Grains",
        "Grant programs",
        "Grants administration",
        "Grazing lands",
        "HIV/AIDS",
        "Harbors",
        "Hawaiian Natives",
        "Hazardous materials transportation",
        "Hazardous substances",
        "Hazardous waste",
        "Health",
        "Health care",
        "Health facilities",
        "Health insurance",
        "Health maintenance organizations (HMO)",
        "Health professions",
        "Health records",
        "Health statistics",
        "Heart diseases",
        "Highway safety",
        "Highways and roads",
        "Historic preservation",
        "Hobbies",
        "Hogs",
        "Holding companies",
        "Holidays",
        "Home improvement",
        "Homeless",
        "Homesteads",
        "Homeworkers",
        "Hospice care",
        "Hospitals",
        "Hostages",
        "Household appliances",
        "Housing",
        "Housing standards",
        "Human research subjects",
        "Hunting",
        "Immigration",
        "Immunization",
        "Imports",
        "Income (SSI)",
        "Income taxes",
        "Indemnity payments",
        "Indexing Terms",
        "Indians",
        "Indians-arts and crafts",
        "Indians-business and finance",
        "Indians-claims",
        "Indians-education",
        "Indians-enrollment",
        "Indians-judgment funds",
        "Indians-lands",
        "Indians-law",
        "Indians-tribal government",
        "Individuals with disabilities",
        "Industrial safety",
        "Infants and children",
        "Insulation",
        "Insurance",
        "Insurance companies",
        "Intergovernmental relations",
        "Intermodal transportation",
        "International boundaries",
        "International organizations",
        "Inventions and patents",
        "Investigations",
        "Investment companies",
        "Investments",
        "Irrigation",
        "Job Corps",
        "Jukeboxes",
        "Juvenile delinquency",
        "Kidney diseases",
        "Labeling",
        "Labor",
        "Labor management relations",
        "Labor unions",
        "Laboratories",
        "Land sales",
        "Lasers",
        "Law",
        "Law enforcement",
        "Law enforcement officers",
        "Lawyers",
        "Lead poisoning",
        "Legal services",
        "Leprosy (Hansen's disease)",
        "Libraries",
        "Lie detector tests",
        "Life insurance",
        "Liquors",
        "Livestock",
        "Loan programs",
        "Lobbying",
        "Longshore and harbor workers",
        "Lotteries",
        "Low and moderate income housing",
        "Lung diseases",
        "Manpower",
        "Manpower training programs",
        "Manufactured homes",
        "Margarine",
        "Marine mammals",
        "Marine resources",
        "Marine safety",
        "Marital status discrimination",
        "Maritime carriers",
        "Marketing agreements",
        "Marketing quotas",
        "Mass transportation",
        "Maternal and child health",
        "Measurement standards",
        "Meat and meat products",
        "Meat inspection",
        "Medicaid",
        "Medical and dental schools",
        "Medical devices",
        "Medical research",
        "Medicare",
        "Mental health programs",
        "Metals",
        "Metric system",
        "Micrographics",
        "Migrant labor",
        "Military academies",
        "Military air transportation",
        "Military law",
        "Military personnel",
        "Milk",
        "Milk marketing orders",
        "Mine safety and health",
        "Mineral resources",
        "Mineral royalties",
        "Miners",
        "Mines",
        "Minimum wages",
        "Minority businesses",
        "Monuments and memorials",
        "Mortgage insurance",
        "Mortgages",
        "Motion pictures",
        "Motor carriers",
        "Motor vehicle pollution",
        "Motor vehicle safety",
        "Motor vehicles",
        "Moving of household goods",
        "Museums",
        "Music",
        "National banks",
        "National defense",
        "National forests",
        "National parks",
        "National trails system",
        "National wild and scenic rivers system",
        "Natural gas",
        "Natural resources",
        "Navigation (air)",
        "Navigation (water)",
        "News media",
        "Newspapers and magazines",
        "Noise control",
        "Nonprofit organizations",
        "Nuclear energy",
        "Nuclear materials",
        "Nuclear power plants and reactors",
        "Nuclear vessels",
        "Nursery stock",
        "Nursing homes",
        "Nutrition",
        "Nuts",
        "Occupational safety and health",
        "Oceanographic research vessels",
        "Oil and gas exploration",
        "Oil and gas reserves",
        "Oil imports",
        "Oil pollution",
        "OilSeeds",
        "Oils and fats",
        "Old-age, Survivors and Disability Insurance",
        "Ophthalmic goods and services",
        "Organization and functions (Government agencies)",
        "Over-the-counter drugs",
        "Packaging and containers",
        "Parking",
        "Passenger vessels",
        "Passports and visas",
        "Peer Review Organizations (PRO)",
        "Penalties",
        "Pension insurance",
        "Pensions",
        "Personally identifiable information",
        "Pesticides and pests",
        "Petroleum",
        "Petroleum allocation",
        "Petroleum price regulations",
        "Pets",
        "Pipeline safety",
        "Pipelines",
        "Plant diseases and pests",
        "Plants",
        "Plastics materials and synthetics",
        "Poison prevention",
        "Political activities (Government employees)",
        "Political affiliation discrimination",
        "Political candidates",
        "Political committees and parties",
        "Postal Service",
        "Poultry and poultry products",
        "Prescription drugs",
        "Presidential documents",
        "Price controls",
        "Price support programs",
        "Printing",
        "Prisoners",
        "Prisoners of war",
        "Prisons",
        "Privacy",
        "Private schools",
        "Probation and parole",
        "Proclamations",
        "Public assistance programs",
        "Public health",
        "Public housing",
        "Public lands",
        "Public lands-classification",
        "Public lands-grants",
        "Public lands-mineral resources",
        "Public lands-rights-of-way",
        "Public lands-sale",
        "Public lands-withdrawal",
        "Quarantine",
        "Radiation protection",
        "Radio",
        "Radioactive materials",
        "Railroad employees",
        "Railroad retirement",
        "Railroad safety",
        "Railroad unemployment insurance",
        "Railroads",
        "Range management",
        "Real property acquisition",
        "Reclamation",
        "Recordings",
        "Recreation and recreation areas",
        "Recycling",
        "Refugees",
        "Religious discrimination",
        "Relocation assistance",
        "Rent subsidies",
        "Reporting and recordkeeping requirements",
        "Research",
        "Reservoirs",
        "Retirement",
        "Revenue sharing",
        "Rights-of-way",
        "Rivers",
        "Rubber and rubber products",
        "Rural areas",
        "Safety",
        "Satellites",
        "Savings associations",
        "Scholarships and fellowships",
        "School breakfast and lunch programs",
        "School construction",
        "Schools",
        "Science and technology",
        "Scientific equipment",
        "Scientists",
        "Seafood",
        "Seals and insignia",
        "Seamen",
        "Search warrants",
        "Seashores",
        "Securities",
        "Security measures",
        "See",
        "Seeds",
        "Seismic safety",
        "Seizures and forfeitures",
        "Selective Service System",
        "Sewage disposal",
        "Sex discrimination",
        "Signs and symbols",
        "Silver",
        "Small businesses",
        "Smoking",
        "Social Security",
        "Social security",
        "Soil conservation",
        "Solar energy",
        "Space transportation and exploration",
        "Specific animals",
        "Specific chemicals",
        "Specific commodities",
        "Specific countries",
        "Specific dairy products",
        "Specific diseases",
        "Specific drugs",
        "Specific foods",
        "Specific fruits",
        "Specific gases",
        "Specific grains",
        "Specific hazardous substances",
        "Specific industries",
        "Specific metals",
        "Specific military departments",
        "Specific vegetables",
        "Spices and flavorings",
        "State and local governments",
        "Statistics",
        "Stockyards",
        "Strategic and critical materials",
        "Student aid",
        "Students",
        "Sugar",
        "Sunshine Act",
        "Superfund",
        "Supplemental Security Income (SSI)",
        "Surety bonds",
        "Surface mining",
        "Surplus Government property",
        "Surplus agricultural commodities",
        "Tax treaties",
        "Taxes",
        "Tea",
        "Teachers",
        "Technical assistance",
        "Telecommunications",
        "Telegraph",
        "Telephone",
        "Television",
        "Textiles",
        "Time",
        "Tires",
        "Tobacco",
        "Toys",
        "Trade adjustment assistance",
        "Trade agreements",
        "Trade names",
        "Trade practices",
        "Trade practices (02",
        "Trademarks",
        "Traffic regulations",
        "Trails",
        "Transportation",
        "Travel",
        "Travel and transportation expenses",
        "Travel restrictions",
        "Treaties",
        "Trusts and trustees",
        "Truth in lending",
        "Truth in savings",
        "Underground mining",
        "Unemployment compensation",
        "Uniform System of Accounts",
        "United States investments abroad",
        "Uranium",
        "Urban areas",
        "Urban renewal",
        "Utilities",
        "Vegetable juices",
        "Vegetables",
        "Venereal diseases",
        "Vessels",
        "Veterans",
        "Veterinarians",
        "Vocational education",
        "Vocational rehabilitation",
        "Voluntary standards",
        "Volunteers",
        "Voting rights",
        "Wages",
        "War claims",
        "War risk insurance",
        "Warehouses",
        "Warranties",
        "Waste treatment and disposal",
        "Watches and jewelry",
        "Water bank program",
        "Water pollution control",
        "Water resources",
        "Water supply",
        "Watersheds",
        "Waterways",
        "Weather",
        "Whistleblowing",
        "Wilderness areas",
        "Wildlife",
        "Wildlife refuges",
        "Wine",
        "Wiretapping and electronic surveillance",
        "Women",
        "Work Incentive Programs (WIN)",
        "Workers' compensation",
        "X-rays",
        "Youth",
        "Zoning",
      ]
      
      true_topic_hash = {}
      true_topics.each{|t| true_topic_hash[t] = 1}
      
      Topic.all(:order => "name").each do |topic|
        puts [topic.name, topic.entries_count, (true_topic_hash[topic.name] || 0)].join("\t")
      end
    end
  end
end