---
api_key: <%= Rails.application.credentials.dig(:honeybadger, :api_key) %>
debug: true
exceptions:
  ignore:
    - 'Content::PublicInspectionImporter::BatchedDocumentImporter::BatchTimeoutError'
  ignored_user_agents: [/ScanAlert/]
revision: <%= Settings.container.revision %>
