shared: &shared
  api_keys:
    google_maps_geocode: <%= ENV['GOOGLE_MAPS_GEOCODE'] %>
    flickr: <%= ENV['FLICKR'] %>
    flickr_secret: <%= ENV['FLICKR_SECRET'] %>
    honeybadger: <%= ENV['HONEYBADGER'] %>
    open_calais: <%= ENV['OPEN_CALAIS'] %>

  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    cloudfront_access_key_id: <%= ENV['CLOUDFRONT_AWS_ACCESS_KEY_ID'] %>
    cloudfront_secret_access_key: <%= ENV['CLOUDFRONT_AWS_SECRET_ACCESS_KEY'] %>

  email_salt: <%= ENV['EMAIL_SALT'] %>

  gpo_sftp:
    username: <%= ENV['GPO_SFTP_USER'] %>
    password: <%= ENV['GPO_SFTP_PASSWORD'] %>
  
  gpo_historical_images_sftp:
    username: <%= ENV['GPO_HISTORICAL_IMAGES_SFTP_USER'] %>
    password: <%= ENV['GPO_HISTORICAL_IMAGES_SFTP_PASSWORD'] %>

  public_inspection:
    api_base_uri: <%= ENV['PIL_API_BASE_URL'] %>
    api_user_name: <%= ENV['PIL_API_USER'] %>
    api_password: <%= ENV['PIL_API_PASSWORD'] %>

  redis:
    host: <%= ENV['REDIS_PORT_6379_TCP_ADDR'] || '127.0.0.1' %>
    port: <%= ENV['REDIS_PORT_6379_TCP_PORT'] || 6379 %>
    db: <%= ENV['REDIS_DB'] || 0 %>

  regulations_dot_gov:
    v4_api_key: <%= ENV['REGULATIONS_DOT_GOV_V4_API_KEY'] || 'test_key' %>

  sendgrid:
    username: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>

  secret_key_base: <%= ENV['RAILS_SESSION_KEY'] || '184245f5e2dc60d22a9ce93ef97daa3a70f7d2eebeea02dc86ddf5173fb353189e8295b35960febd3adde26dfbb2d1ce8c17c422bc71c3580d147f8b5970f689' %>

development:
  <<: *shared
  secret_key_base: 16af71f691e4faa336435bc8154e473d33b9fdcd290e1be2a271841fc578f6ce12dec6c4abf1c75c8b347d3e407ba9562d9f4b6e517bf8810de53c41c19b290d

test:
  <<: *shared
  secret_key_base: 16af71f691e4faa336435bc8154e473d33b9fdcd290e1be2a271841fc578f6ce12dec6c4abf1c75c8b347d3e407ba9562d9f4b6e517bf8810de53c41c19b290d

staging:
  <<: *shared

production:
  <<: *shared
