app:
  aws:
    s3:
      buckets:
        agency_logos: agency-logos.example.com
        image_holding_tank: image-holding-tank.example.com
        image_variants: img.example.com
        original_images: img-orig.example.com
        private_images: private.images.example.com
        public_images: images.example.com
        public_inspection: public-inspection.example.com
      host_aliases:
        agency_logos: agency-logos.example.com
        image_variants: img.example.com
        private_images: s3.amazonaws.com
        public_images: images.example.com
        public_inspection: public-inspection.example.com
  deliver_daily_import_email: true
  deliver_late_content_notifications: true
  deployment_environment: blue
  google_analytics:
    update_document_counts: true
  images:
    download_daily_images_from_sftp: false
    download_historical_images_from_sftp: false
    download_and_process_from_holding_tank: false
    environments_requiring_image_download: ['Staging', 'Production']
    store_in_filesystem: false
  import:
    content: true
    public_inspection: true
  public_inspection_documents:
    page_view_start_date: "2020-10-09"
  regulations_dot_gov:
    update_documents: true
    update_dockets: true
  reindex_all_agency_name_entries: false

# host, password and username are retrived from credentials
# development environment uses ENV vars for these so keys are defined here
database:
  adapter: mysql2
  encoding: utf8
  host:
  name: federal_register_api_core
  password:
  port: 3306
  reconnect: true
  username:

# host is retrived from credentials
# development/test environment uses ENV vars for these that key is defined here
elasticsearch:
  host:
  trace: false
  enabled: true
  entry_index_shards: 1
  public_inspection_document_index_shards: 1


# feature flags should ideally be short lived switches before full rollout
# long-lived switches should placed in the `app` settings block
feature_flags:
  # TODO: this is now the default and we should be able to remove all the old code
  use_carrierwave_images_in_api: true

lograge:
  enabled: true

# this can be turned on during a rails upgrade to detect deprecations
# ex: enable on staging to check the daily imports, etc.
rails:
  report_deprecations: false

# host is retrived from credentials
# development/test environment uses ENV vars for this so key is defined here
redis:
  db: 0
  host:
  port: 6379

open_calais:
  daily_api_call_limit: 500
  throttle:
    concurrency: 1
    at: 1
    per: 1

paperclip:
  abort_on_s3_error: false

prince:
  # expected to be set by helm/deployment
  host: http://prince-xml-14.ofr-prod.svc.cluster.local
  port: 3000

services:
  fr:
    web:
      base_url: https://www.federalregister.gov

sidekiq:
  # kilobytes (integer) like 1048576 (1GB)
  memory_threshold: 1048576

regulations_dot_gov:
  api_base_url: "https://api-staging.regulations.gov/v4"
  throttle:
    at: 1
    per: 5

varnish:
  # expected to be set by helm/deployment
  host: varnish.fr-prod.svc.cluster.local
  port: 6082
