#!/bin/bash
set -ex

if ! [ "$CONTAINER_ROLE" = "worker" ]; then
  rm -rf /etc/my_init.d/elasticsearch
  rm -rf /etc/my_init.d/migrate
  rm -rf /etc/my_init.d/varnish
  rm -rf /etc/my_init.d/whenever
fi
