app:
  aws:
    s3:
      buckets:
        public_inspection: public-inspection.fr2.local
      host_aliases:
        public_inspection: public-inspection.fr2.local
  deliver_daily_import_email: false
  deliver_late_content_notifications: false
  google_analytics:
    update_document_counts: false
  import:
    content: false
    public_inspection: false
  public_inspection_documents:
    index_since_date: "2019-04-08"
  regulations_dot_gov:
    update_documents: false
    update_dockets: false

container:
  role: worker

lograge:
  enabled: false

regulations_dot_gov:
  api_base_url: "https://api-staging.regulations.gov/v4"

services:
  fr:
    web:
      base_url: https://dev-fr2.criticaljuncture.org
