app:
  aws:
    s3:
      buckets:
        agency_logos: agency-logos.federalregister.gov
        image_holding_tank: image-holding-tank.federalregister.gov
        image_variants: img.federalregister.gov
        original_images: img-orig.federalregister.gov
        private_images: private.images.federalregister.gov
        public_images: images.federalregister.gov
        public_inspection: public-inspection.federalregister.gov
      host_aliases:
        agency_logos: agency-logos.federalregister.gov
        image_variants: img.federalregister.gov
        private_images: s3.amazonaws.com
        public_images: images.federalregister.gov
        public_inspection: public-inspection.federalregister.gov
  images:
    download_daily_images_from_sftp: true
    download_and_process_from_holding_tank: true

redis:
  db: 0
