app:
  aws:
    s3:
      buckets:
        agency_logos: agency-logos.fr2.criticaljuncture.org
        image_holding_tank: image-holding-tank.federalregister.gov
        image_variants: img.fr2.criticaljuncture.org
        original_images: img-orig.fr2.criticaljuncture.org
        private_images: private.images.fr2.criticaljuncture.org
        public_images: images.fr2.criticaljuncture.org
        public_inspection: public-inspection.fr2.criticaljuncture.org
      host_aliases:
        agency_logos: agency-logos.fr2.criticaljuncture.org
        image_variants: img.fr2.criticaljuncture.org
        private_images: s3.amazonaws.com
        public_images: images.fr2.criticaljuncture.org
        public_inspection: public-inspection.fr2.criticaljuncture.org
  images:
    download_historical_images_from_sftp: true
    download_and_process_from_holding_tank: true

database:
  name: federal_register_api_core_staging

feature_flags:
  include_pre_1994_docs: true

prince:
  # expected to be set by helm/deployment
  host: http://prince-xml-14.ofr.svc.cluster.local
  port: 3000

redis:
  db: 2

services:
  fr:
    web:
      base_url: https://fr2.criticaljuncture.org

varnish:
  # expected to be set by helm/deployment
  host: varnish.fr.svc.cluster.local
