app:
  images:
    store_in_filesystem: true
  public_inspection_documents:
    index_since_date: "2019-04-08"
    page_view_start_date: "2020-10-02"

elasticsearch:
  host: http://admin:admin@elasticsearch:9200

lograge:
  enabled: false

redis:
  host: 127.0.0.1
