version: '2'

services:
  web:
    image: $CI_IMAGE
    extends:
      file: shared.yml
      service: web
    environment:
      RAILS_ENV: test
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      DB_STRUCTURE_ACCESS_KEY: ''
      DB_STRUCTURE_SECRET: ''
    links:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - /tmp/test-results:/home/app/tmp/test-results
  mysql:
    extends:
      file: shared.yml
      service: mysql

  redis:
    extends:
      file: shared.yml
      service: redis

  elasticsearch:
    extends:
      file: shared.yml
      service: elasticsearch
    environment:
      - plugins.security.ssl.http.enabled=false
      - plugins.security.disabled=true
      - plugins.ml_commons.native_memory_threshold=100
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - plugins.ml_commons.only_run_on_ml_node=false
      - discovery.type=single-node
      - http.host=0.0.0.0
      - network.host=0.0.0.0


