services:
  web:
    image: $CI_IMAGE
    extends:
      file: shared.yml
      service: web
    environment:
      - RAILS_ENV=test
      - DB_STRUCTURE_ACCESS_KEY
      - DB_STRUCTURE_SECRET
      - ELASTICSEARCH_HOST=http://admin:admin@elasticsearch:9200
    links:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - /tmp/test-results:/home/app/tmp/test-results  
  mysql:
    extends:
      file: shared.yml
      service: mysql

  redis:
    extends:
      file: shared.yml
      service: redis

  elasticsearch:
    extends:
      file: shared.yml
      service: elasticsearch
    environment:
      - opendistro_security.ssl.http.enabled=false
