version: '2'

services:
  web:
    image: 264372021245.dkr.ecr.us-east-1.amazonaws.com/federalregister-api-core:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      WEB_PORT: 3000
      PASSENGER_MIN_INSTANCES: 2
      # intended for the bin/wait_for_mysql script only
      MYSQL_PORT_3306_TCP_ADDR: mysql
      REDIS_PORT_6379_TCP_ADDR: redis
      HONEYBADGER_API_KEY: ''
      SECRET_KEY_BASE: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      ELASTICSEARCH_HOST: http://admin:admin@elasticsearch:9200
      SETTINGS__DATABASE__HOST: mysql
      SETTINGS__REDIS__HOST: redis
    restart: always

  mysql:
    image: mysql:8
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  redis:
    image: redis:6-alpine
    expose:
      - "6379"

  elasticsearch:
    image: opensearchproject/opensearch:2.14.0
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - script.painless.regex.enabled=true
